//Generated by Generator
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;



namespace Enchere_AP4.Models
{
   public class Produit
   {
        #region attributes 
        private int _id;
        private string _nom, _photo;
        private double _prix;
        private ObservableCollection<Magasin> _collMagasin;
        private ObservableCollection<Enchere> _collEnchere;

        public static ObservableCollection<Produit> CollProduit = new ObservableCollection<Produit>();
        #endregion    
        #region constructor 

        public Produit(int id,string nom,string photo,double prix) 
        {
            Id = id;
            Nom = nom;
            Photo = photo;
            Prix = prix;

            CollMagasin = new ObservableCollection<Magasin>();

            

            CollProduit.Add(this);
        }

        #endregion
        #region get/set 

        public int Id { get => _id; set => _id = value; }
        public string Nom { get => _nom; set => _nom = value; }
        public string Photo { get => _photo; set => _photo = value; }
        public double Prix { get => _prix; set => _prix = value; }
        public ObservableCollection<Magasin> CollMagasin { get => _collMagasin; set => _collMagasin = value; }
        public ObservableCollection<Enchere> CollEnchere { get => _collEnchere; set => _collEnchere = value; }

        #endregion
        #region methods 


        private void LoadEncheres()
        {
            if(Enchere.CollEnchere != null && Enchere.CollEnchere.Count > 0)
            {
                foreach(Enchere enchere in Enchere.CollEnchere)
                {
                    if (enchere.LeProduit.Id == Id)
                        this._collEnchere.Add(enchere);
                }
            }

        }
        #endregion


    }
}
